//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Forms&gt;
        ///  &lt;Form&gt;
        ///    &lt;id&gt;1&lt;/id&gt;
        ///    &lt;name&gt;Triangle&lt;/name&gt;    
        ///  &lt;/Form&gt;
        ///  &lt;Form&gt;
        ///    &lt;id&gt;2&lt;/id&gt;
        ///    &lt;name&gt;Segment&lt;/name&gt;
        ///  &lt;/Form&gt;
        ///  &lt;Form&gt;
        ///    &lt;id&gt;3&lt;/id&gt;
        ///    &lt;name&gt;Rectangle&lt;/name&gt;
        ///  &lt;/Form&gt;
        ///  &lt;Form&gt;
        ///    &lt;id&gt;4&lt;/id&gt;
        ///    &lt;name&gt;Polygon&lt;/name&gt;
        ///  &lt;/Form&gt;
        ///  &lt;Form&gt;
        ///    &lt;id&gt;5&lt;/id&gt;
        ///    &lt;name&gt;Group&lt;/name&gt;
        ///  &lt;/Form&gt;
        ///  &lt;Form&gt;
        ///    &lt;id&gt;6&lt;/id&gt;
        ///    &lt;name&gt;Circle&lt;/name&gt;
        ///  &lt;/Form&gt;
        ///&lt;/Forms&gt;.
        /// </summary>
        internal static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
    }
}
